# Generated by Django 5.1.4 on 2024-12-28 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sorteos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_especial', models.IntegerField()),
                ('rondas_para_especial', models.IntegerField(default=10)),
                ('ronda_actual', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Configuración del Sorteo',
                'verbose_name_plural': 'Configuraciones del Sorteo',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='item',
            name='probabilidad',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='item',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
