# Generated by Django 5.1.4 on 2024-12-28 22:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sorteos', '0002_configuracionsorteo_item_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('presente', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='item',
            name='probabilidad',
        ),
        migrations.RemoveField(
            model_name='item',
            name='valor',
        ),
        migrations.AddField(
            model_name='item',
            name='fecha_sorteo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sorteos.persona'),
        ),
    ]
