# Generated by Django 5.1.4 on 2024-12-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sorteos', '0004_remove_persona_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ha_ganado',
            field=models.BooleanField(default=False),
        ),
    ]
