# Generated by Django 5.1.4 on 2024-12-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sorteos', '0005_persona_ha_ganado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='presente',
        ),
    ]
